MODEL_WEIGHTS_PATH = "model_weights"
TRAINING_IMAGES_PATH = "datasets/train-images-idx3-ubyte"
TRAINING_LABELS_PATH = "datasets/train-labels-idx1-ubyte"
TEST_IMAGES_PATH = "datasets/t10k-images-idx3-ubyte"
TEST_LABELS_PATH = "datasets/t10k-labels-idx1-ubyte"